---

name: 👥 Request to join the triagers team
description: Triage issues to help us maintain aiohttp and the rest of aio-libs

title: Please add me ({{ username }} — replace this) to the triagers team
labels:
- help wanted
assignees:
- bdraco
- Dreamsorcerer
- webknjaz
projects:
- aio-libs/4  # this doesn't actually work and is handled in-project workflows
type: Meta

body:
- type: markdown
  attributes:
    value: |
      **Thanks for taking a minute to think of becoming our triager!**

      > [!caution]
      > Read the [aio-libs Code of Conduct][CoC] first. You'll need to
      > follow it. Just like everyone else.

      _Please fill out the form below with as many precise details
      as possible. Use your own words, not a copy of an LLM output._

      > [!important]
      > If unsure, participate in the community first. Check out our
      > Matrix space and rooms. Help other people use our projects. This
      > will set you on the right path!

      [CoC]: https://github.com/pypa/.github/blob/main/CODE_OF_CONDUCT.md

- type: textarea
  attributes:
    label: What's your background?
    description: >-
      What do you know about (or how have you used) `aiohttp`,
      `asyncio` and Python in general?

- type: textarea
  attributes:
    label: What's your motivation?
    description: >-
      Why/how do you want to help?
      What do you expect?

- type: checkboxes
  attributes:
    label: Code of Conduct
    description: |
      Read the [aio-libs Code of Conduct][CoC] first.

      [CoC]: /aio-libs/.github/blob/master/CODE_OF_CONDUCT.md
    options:
    - label: >-
        I am aware that participants in this repository must follow the
        aio-libs Code of Conduct.
      required: true

...
